export default Object.freeze({
    EDIT_PROFILE_FIELD: 'editProfileField',
    EDIT: 'edit',
    CREATOR: 'creator',
    LINK: 'link',
    YOUTUBE_LINK: 'youtubeLink',
    INSTAGRAM_LINK: 'instagramLink',
    MANAGE_ACCOUNT: 'manageAccount',
    GUIDELINES: 'guidelines',
    TERMS: 'terms',
    EULA: 'eula',
    PRIVACY: 'privacy',
    COPYRIGHT: 'copyright',
    ADMISSION: 'admission',
    BUY_LINK: 'buyLink',
    DONATION: 'donation',
    REVIEWS: 'reviews',
    ADS: 'ads',
    SUBSCRIPTIONS: 'subscriptions',
    DRAFTS: 'drafts',
    DELETE_PROFILE: 'deleteProfile',
    SETTINGS_SCREEN: 'settingsScreen',
    MARKET: 'market',
    PROFILE_OTHER: 'profileOther',
    USER_POSTS: 'userPosts',
    SELLER: 'phlokkMarketTools',
    CHAT_SINGLE: 'chatSingle',
    FEED: 'feed',
    HOME: 'home',
    MESSAGES: 'messages',
    RELATIONSHIP: 'relationship',
    REPORTS: 'reports',
    SETTING_SHEET: 'settingsSheet',
    
})