export const types = {
  USER_STATE_CHANGE: "USER_STATE_CHANGE",
  GET_ALL_POST_DATA: "GET_ALL_POST_DATA",
  // User Post and Feed screen
  SEND_REQUEST_GET_USER: "SEND_REQUEST_GET_USER",
  SEND_REQUEST_GET_USER_SUCCESS: "SEND_REQUEST_GET_USER_SUCCESS",
  SEND_REQUEST_GET_USER_FAILURE: "SEND_REQUEST_GET_USER_FAILURE",
  CURRENT_USER_POSTS_UPDATE: "CURRENT_USER_POSTS_UPDATE",
  CHATS_SET: "CHATS_SET",
  // Market Creator Data 
  SEND_REQUEST_GET_MARKET_CREATOR: "SEND_REQUEST_GET_MARKET_CREATOR",
  SEND_REQUEST_GET_MARKET_CREATOR_SUCCESS:
  "SEND_REQUEST_GET_MARKET_CREATOR_SUCCESS",
  SEND_REQUEST_GET_MARKET_CREATOR_FAILURE:
  "SEND_REQUEST_GET_MARKET_CREATOR_FAILURE",


  // Models
  MODAL_OPEN_COMMENT_SECTION: "MODAL_OPEN_COMMENT_SECTION",
  MODAL_OPEN_SETTINGS: "MODAL_OPEN_SETTINGS",
  MODAL_OPEN_SETTINGS_SHEET_SECTION: "MODAL_OPEN_SETTINGS_SHEET_SECTION",
  CLEAR_MODAL: "CLEAR_MODAL",
  MODAL_OPEN_GIFTING_SECTION: "MODAL_OPEN_GIFTING_SECTION",
};
