export const types = {
  USER_STATE_CHANGE: "USER_STATE_CHANGE",
  GET_ALL_POST_DATA: "GET_ALL_POST_DATA",
  // User Post and Feed screen
  CURRENT_USER_POSTS_UPDATE: "CURRENT_USER_POSTS_UPDATE",
  // Market Creator Data
  SEND_REQUEST_GET_MARKET_CREATOR: "SEND_REQUEST_GET_MARKET_CREATOR",
  SEND_REQUEST_GET_MARKET_CREATOR_SUCCESS:
    "SEND_REQUEST_GET_MARKET_CREATOR_SUCCESS",
  SEND_REQUEST_GET_MARKET_CREATOR_FAILURE:
    "SEND_REQUEST_GET_MARKET_CREATOR_FAILURE",
  SET_POSTS_LIKES: "SET_POSTS_LIKES",
  UPDATE_POST_LIKES: "UPDATE_POST_LIKES",
};
